### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/wallet-connect-sdk#20]
the formatting of both the core sdk and the react sdk docs is confusing and hard to use... There should be API documentation for all of the methods, their parameters and expected behavior etc rather than what is in place now which is not very helpful for developers trying to use these packages

**Comment by comountainclimber** [comment]
For instance, if you are following the react SDK docs and get here => https://github.com/CityOfZion/wallet-connect-sdk/blob/develop/packages/wallet-connect-sdk-react/README.md#usage 

Just telling the developer to ` // do something` is very unhelpful

**Comment by melanke** [comment]
The documentation must be on the code so we can use TypeDoc to auto generate the doc files

**Comment by melanke** [comment]
Done
