### ISSUE TITLE
Authentication feature

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/wallet-connect-sdk#30]
This issue will implement a feature where the application generates a challenge and sends it to a connected wallet for verification.
1. The application shall have the ability to generate a challenge
2. The application shall have the ability to send the challenge to a connected wallet for verification
3. The wallet shall have the ability to sign the challenge and return the result to the application
4. The application shall have the ability to verify the signature of the user

---
Here’s an example that replicates the message signing and verification functions in Neoline (now that they fixed their broken code). It also uses neon-js to do the actual signing/verification. https://gist.github.com/hal0x2328/2da18eb42ca78a3b5c7f249961a29c26

**Comment by melanke** [comment]
What do you think if both requests were auto-accepted by the wallet?
@lllwvlvwlll @hal0x2328

**Comment by hal0x2328** [comment]
I think the user should always be prompted if their private key will be used for signing a message. If a dApp wants to persist the user's authentication they can always make an expiration time part of the challenge. I don't think we should get too hung up on the challenge/response part of this - really just need to be able to sign arbitrary messages and let each dApp worry about how they will implement their authentication using that capability.

Signature verification can all be done with the public key so no need to prompt the user for that or even send it to the wallet at all.

**Comment by melanke** [comment]
signMessage and verifyMessage, done
