### ISSUE TITLE
Study the need for a dedicated relay server

### ISSUE THREAD

**Issue by picarodias** [CityOfZion/wallet-connect-sdk#35]
## The Issue:

- During implementation in Neon Wallet Desktop, @comountainclimber reported that the third-party relay server seems to be failing when too many people start testing it.
- We might need to reopen the discussion of having our dedicated relay server.

**Comment by melanke** [comment]
This is a real problem, It is really happening, I experienced some lag due to the server yesterday.
Joe had deployed a server a while ago but couldn't compile a new version of the server. I believe we can ask João to help us with that.

**Comment by melanke** [comment]
since we are using the `rc` version it is way better, no need for a dedicated server
