### ISSUE TITLE
Add field verification to methods on connection requests

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/wallet-connect-sdk#40]
This enhancement adds explicit field verification to the payload values on this field to ensure that users are creating valid connection requests:
https://github.com/CityOfZion/wallet-connect-sdk/blob/develop/packages/wallet-connect-sdk-core/src/index.ts#L105

To implement, we should consider a connection request certifier similar to: https://github.com/CityOfZion/wallet-connect-sdk/blob/develop/packages/wallet-connect-sdk-core/src/index.ts#L835

**Comment by melanke** [comment]
done
