### ISSUE TITLE
Provide a mechanism for clients to discover information about the chains the wallet is connected to

### ISSUE THREAD

**Issue by devhawk** [CityOfZion/wallet-connect-sdk#43]
tool dapps (natch) may connect to multiple neo chains - mainnet, testnet, other private testnets, express, etc. It would be useful if a dApp could retrieve information about the chains a wallet is connected to. Nodes would also be nice to know

**Comment by lllwvlvwlll** [comment]
@melanke , it would be nice to have a method which allows a client application to request the network and a representative node.  This is particularly helpful for privatenet which can be highly variable.

**Comment by devhawk** [comment]
After thinking about this more, I'd like to suggest using the network magic number as the CAIP-2 reference value instead of "private", at least for the CAIP-10 account identifiers coming back to the dapp from the wallet. So something like `neo3:2453923137:NSGh7RQqCV7arpJjijqqHnT9cH6rJTGvYh` instead of `neo3:private:NSGh7RQqCV7arpJjijqqHnT9cH6rJTGvYh`. 

Theoretically, you could use this same syntax for mainnet and testnet, but I assume that would break existing dApps. I doubt there are many (if any) Neo dApps out there making significant use of the `neo3:private` identifier, so changing the format of privatenet account identifiers would have a smaller impact.

In this approach, `neo3:private` would still be a valid chain identifier for the purposes of specifying chain permissions in the dApp. This allows for the dApp to connect to a privatenet wallet without having to know the network id of the privatenet in advance.

**Comment by devhawk** [comment]
FYI, I tried hacking this up, but the official WC SDK (2.0.0-beta.22) doesn't allow it. I get a `Unhandled Rejection (Error): Invalid accounts with mismatched chains: neo3:2453923137:NQUqF2um6ywgvZdp9HwhFD1R5bMSiskMBC` error

**Comment by devhawk** [comment]
I *was* able to add the network magic value to the SessionState object passed to client.approve

wallet side:
``` js
const response = {
  state: {accounts, magic},
  metadata: options.appMetadata,
}
const session = await wcClient.approve({proposal, response})
```

session.state value on dapp side:
``` json
{
  accounts: [
    "neo3:private:NQUqF2um6ywgvZdp9HwhFD1R5bMSiskMBC",
  ],
  magic: 2453923137,
}
```

**Comment by melanke** [comment]
Hi, sorry, I didn't see this issue, I had too much notifications on my GH.

I didn't understand the usecase, I thought the only usecase for "private" would be to allow developers to test their dapps locally with neo-express, and for this situation the developer would simply setup the wallet and dapp to use the same network, which would be simple with the current "neo3:private" approach.

Your usecase is for dapps that connects with multiple networks and needs to inform the wallet to connect on the same network as it is connected to, correct?

**Comment by devhawk** [comment]
yes, something like that @melanke. dev tools like DevTracker connect to multiple chains at once - which I understand is atypical for dApps while being common for dev tools

**Comment by melanke** [comment]
You can use getNetworkVersion method
