### ISSUE TITLE
Can't connect using `signMessage` method on initialization

### ISSUE THREAD

**Issue by mfbz** [CityOfZion/wallet-connect-sdk#44]
Hi all and thanks for the fantastic library.

https://github.com/CityOfZion/wallet-connect-sdk/blob/0bf41eb1d003a15291d9c15a88af7202928b7ec1/packages/wallet-connect-sdk-core/src/index.ts#L105

I would like to report you that if i use some methods like 'signMessage', it cannot connect via neon-wallet.
When inserting the URL and clicking "connect" it just does nothing.

On the other side, if i only use the 'invokeFunction' method, I'm prompted to connect my dapp and everything works correctly.

**Comment by melanke** [comment]
Hi @mfbz it is possible that this method was not implemented on the wallet yet, can you try again?

**Comment by melanke** [comment]
I am gonna close, but please, reopen if you think this is still a bug, sorry for the delay.
