### ISSUE TITLE
Crypsydra dApp in README does not work

### ISSUE THREAD

**Issue by mike-petrov** [CityOfZion/wallet-connect-sdk#56]
README file contains a demonstration of using a wallet with Crypsydra dApp. But below there is a link to check the application yourself:

"This example is showing [Crypsydra dApp](https://github.com/east-side-cryps/crypsydra-web) connecting with [Aero Wallet](https://aero.coz.io/)"

This is pretty confusing because the repository use the first version of WC which is outdated. So the demo site is not working: [crypsydra.vercel.app](https://crypsydra.vercel.app/)

<img width="653" alt="image" src="https://user-images.githubusercontent.com/32885629/198101762-a07af0b8-a239-462a-b85c-7d2447cd0efb.png">

**Comment by melanke** [comment]
Sorry for the delayed response. This links were updated/removed on the documentation.
