### ISSUE TITLE
Usage Guide link in README not working for npmjs site

### ISSUE THREAD

**Issue by mike-petrov** [CityOfZion/wallet-connect-sdk#94]
Try to go to the link Usage Guide in [npmjs](https://www.npmjs.com/package/@cityofzion/wallet-connect-sdk-react#usage)

For github site it [works](https://github.com/CityOfZion/wallet-connect-sdk/blob/main/README.md). I think the problem with relative link.

**Comment by melanke** [comment]
Fixed, thanks for reporting
